package com.robindrew.codegenerator.api.sql.builder.hsqldb;

import com.robindrew.codegenerator.api.sql.builder.ISqlBuilder;
import com.robindrew.codegenerator.api.sql.builder.SqlBuilder;

public class HsqldbSqlBuilder extends SqlBuilder implements IHsqldbSqlBuilder {

	@Override
	public ISqlBuilder createTable(String table) {
		return sql("CREATE CACHED TABLE ").table(table);
	}

	@Override
	public ISqlBuilder autoIncrement() {
		return sql(" GENERATED BY DEFAULT AS IDENTITY(START WITH 1)");
	}

	@Override
	public ISqlBuilder value(byte[] value) {
		throw new UnsupportedOperationException();
	}

}
